name: Build
<<<<<<< HEAD
<<<<<<< HEAD
=======
# Tests image build
>>>>>>> b9db68c4634a9bdef9339dcde586fa34c650633c
=======
# Tests image build
>>>>>>> b9db68c4634a9bdef9339dcde586fa34c650633c

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> b9db68c4634a9bdef9339dcde586fa34c650633c
# Environment variables available to all jobs and steps in this workflow
env:
  IMAGE_TAG: groov-in-c

<<<<<<< HEAD
>>>>>>> b9db68c4634a9bdef9339dcde586fa34c650633c
=======
>>>>>>> b9db68c4634a9bdef9339dcde586fa34c650633c
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
<<<<<<< HEAD
<<<<<<< HEAD

    - name: Build bot (x86_64)
=======
      
    # Build
    - name: Build bot
>>>>>>> b9db68c4634a9bdef9339dcde586fa34c650633c
=======
      
    # Build
    - name: Build bot
>>>>>>> b9db68c4634a9bdef9339dcde586fa34c650633c
      run: chmod +x ./build.sh && ./build.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ConcordBot-x86_64
        path: ConcordBot
