name: Docker Build
# Tests image build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Environment variables available to all jobs and steps in this workflow
env:
  IMAGE_TAG: groov-in-c


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    # Build
    - name: Build Docker image
      run: |        
        docker build -t ${IMAGE_TAG}:${GITHUB_SHA} .
