# This is a basic workflow to help you get started with Actions

name: Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install libraries
        run: apt-get install -y build-essential wget libcurl4-openssl-dev libssl-dev --yes

      # Runs a single command using the runners shell
      - name: Installs & Create Orca
        run: git clone https://github.com/cee-studio/orca.git && cd orca && make && make install && cd ../

      # Runs a set of commands using the runners shell
      - name: Build main.c
        run: |
          clang main.c -o main.out -Wall -Wextra -Werror -g -pthread -ldiscord -lcurl -lcrypto -lpthread -lm -lsqlite3 && ./main.out
