name: Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install libraries
        run: sudo apt-get install -y build-essential wget libcurl4-openssl-dev libssl-dev sqlite3
      
      - name: Downloads Orca
        run: git clone https://github.com/cee-studio/orca.git
        
      - name: Move files
        run: mv websockets.c orca/common/ && mv discord-gateway.c orca/
      
      - name: Builds Orca
        run: make orca && make install orca
      
      - name: Build main.c
        run: clang main.c -o main.out -Wall -Wextra -Werror -g -pthread -ldiscord -lcurl -lcrypto -lpthread -lm -lsqlite3 && ./main.out
